/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogicaPresentacion;

import java.awt.BorderLayout;

/**
 *
 * @author dcast
 */
public class Empleado extends javax.swing.JFrame {

    /**
     * Creates new form Prueba
     */
    public Empleado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInicio = new javax.swing.JButton();
        btnGReportes = new javax.swing.JButton();
        botGMaquinas = new javax.swing.JButton();
        btnGJuegos = new javax.swing.JButton();
        lblInicio = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio.setBorder(null);
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 50, 80));

        btnGReportes.setBorder(null);
        btnGReportes.setBorderPainted(false);
        btnGReportes.setContentAreaFilled(false);
        btnGReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnGReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 50, 80));

        botGMaquinas.setBorder(null);
        botGMaquinas.setBorderPainted(false);
        botGMaquinas.setContentAreaFilled(false);
        botGMaquinas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botGMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botGMaquinasActionPerformed(evt);
            }
        });
        getContentPane().add(botGMaquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 50, 80));

        btnGJuegos.setBorder(null);
        btnGJuegos.setBorderPainted(false);
        btnGJuegos.setContentAreaFilled(false);
        btnGJuegos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGJuegosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGJuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 50, 80));

        lblInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Panels.jpg"))); // NOI18N
        getContentPane().add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 770, 500));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo2.jpg"))); // NOI18N
        lblFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botGMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botGMaquinasActionPerformed
        pnlGMaquinas p2 = new pnlGMaquinas();
        p2.setSize(768,472);
        p2.setLocation(0,14);
        
        lblInicio.removeAll();
        lblInicio.add(p2,BorderLayout.CENTER);
        lblInicio.revalidate();
        lblInicio.repaint();
    }//GEN-LAST:event_botGMaquinasActionPerformed

    private void btnGJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGJuegosActionPerformed
        pnlGJuegos p1 = new pnlGJuegos();
        p1.setSize(768,472);
        p1.setLocation(0,14);
        
        lblInicio.removeAll();
        lblInicio.add(p1,BorderLayout.CENTER);
        lblInicio.revalidate();
        lblInicio.repaint();
    }//GEN-LAST:event_btnGJuegosActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
               
        lblInicio.removeAll();
        lblInicio.revalidate();
        //PanelPrin.add(PanelPrin,BorderLayout.CENTER);
        lblInicio.repaint();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnGReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGReportesActionPerformed
        pnlReportes p4 = new pnlReportes();
        p4.setSize(768,472);
        p4.setLocation(0,14);
        
        lblInicio.removeAll();
        lblInicio.add(p4,BorderLayout.CENTER);
        lblInicio.revalidate();
        lblInicio.repaint();
    }//GEN-LAST:event_btnGReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botGMaquinas;
    private javax.swing.JButton btnGJuegos;
    private javax.swing.JButton btnGReportes;
    private javax.swing.JButton btnInicio;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblInicio;
    // End of variables declaration//GEN-END:variables
}
