/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogicaPresentacion;

import javax.swing.JOptionPane;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.util.Timer;
import java.util.TimerTask;
import java.util.Random;

/**
 *
 * @author dcast
 */
public class JfrmJuego extends javax.swing.JFrame { 

    /**
     * Creates new form JfrmJuego
     */
    private int saldoActual, apuesta, contador=0;
    private int[] numsImagenes = new int[3];
    private Timer timer;
    private TimerTask cambiarIconos;
    
    public JfrmJuego() {      
        initComponents();
        this.setLocationRelativeTo(null);
        saldoActual = 0;
        apuesta = 0;
        txtSaldo.setText( Integer.toString(saldoActual) );
        txtApuesta.setText (Integer.toString(apuesta));
    }
       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtApuesta = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        txtIngresarSaldo = new javax.swing.JTextField();
        btnIngresarDinero = new javax.swing.JButton();
        btnCobrar = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnCincomil = new javax.swing.JButton();
        btnMil = new javax.swing.JButton();
        btnQuinientos = new javax.swing.JButton();
        btnCien = new javax.swing.JButton();
        lblImagen3 = new javax.swing.JLabel();
        lblImagen2 = new javax.swing.JLabel();
        lblImagen1 = new javax.swing.JLabel();
        lblJuego = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApuesta.setBackground(new java.awt.Color(0, 0, 0));
        txtApuesta.setFont(new java.awt.Font("Modern No. 20", 1, 16)); // NOI18N
        txtApuesta.setForeground(new java.awt.Color(255, 255, 255));
        txtApuesta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApuesta.setBorder(null);
        getContentPane().add(txtApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 100, -1));
        txtApuesta.setEditable(false);

        txtSaldo.setBackground(new java.awt.Color(0, 0, 0));
        txtSaldo.setFont(new java.awt.Font("Modern No. 20", 1, 16)); // NOI18N
        txtSaldo.setForeground(new java.awt.Color(255, 255, 255));
        txtSaldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSaldo.setBorder(null);
        getContentPane().add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 100, -1));
        txtSaldo.setEditable(false);

        txtIngresarSaldo.setBackground(new java.awt.Color(0, 0, 0));
        txtIngresarSaldo.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        txtIngresarSaldo.setForeground(new java.awt.Color(255, 255, 255));
        txtIngresarSaldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIngresarSaldo.setBorder(null);
        txtIngresarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngresarSaldoActionPerformed(evt);
            }
        });
        getContentPane().add(txtIngresarSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 590, 70, -1));

        btnIngresarDinero.setBorder(null);
        btnIngresarDinero.setBorderPainted(false);
        btnIngresarDinero.setContentAreaFilled(false);
        btnIngresarDinero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIngresarDinero.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ingresar dinero.png"))); // NOI18N
        btnIngresarDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarDineroActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 570, 70, 60));

        btnCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR.jpg"))); // NOI18N
        btnCobrar.setBorder(null);
        btnCobrar.setBorderPainted(false);
        btnCobrar.setContentAreaFilled(false);
        btnCobrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCobrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cobrar.png"))); // NOI18N
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 70, -1));

        btnJugar.setContentAreaFilled(false);
        btnJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnJugar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnJugar.png"))); // NOI18N
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 110, 100));

        btnCincomil.setBorder(null);
        btnCincomil.setContentAreaFilled(false);
        btnCincomil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCincomil.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5K.png"))); // NOI18N
        btnCincomil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincomilActionPerformed(evt);
            }
        });
        getContentPane().add(btnCincomil, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 80, 70));

        btnMil.setBorder(null);
        btnMil.setBorderPainted(false);
        btnMil.setContentAreaFilled(false);
        btnMil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMil.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1K.png"))); // NOI18N
        btnMil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMilActionPerformed(evt);
            }
        });
        getContentPane().add(btnMil, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 70, 70));

        btnQuinientos.setBorder(null);
        btnQuinientos.setBorderPainted(false);
        btnQuinientos.setContentAreaFilled(false);
        btnQuinientos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnQuinientos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/500.png"))); // NOI18N
        btnQuinientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuinientosActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuinientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 70, 70));

        btnCien.setBorder(null);
        btnCien.setBorderPainted(false);
        btnCien.setContentAreaFilled(false);
        btnCien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCien.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/100.png"))); // NOI18N
        btnCien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCienActionPerformed(evt);
            }
        });
        getContentPane().add(btnCien, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 80, 70));

        lblImagen3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblImagen3.setIconTextGap(0);
        getContentPane().add(lblImagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 80, 70));

        lblImagen2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblImagen2.setIconTextGap(0);
        getContentPane().add(lblImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 80, 70));

        lblImagen1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblImagen1.setIconTextGap(0);
        getContentPane().add(lblImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 80, 70));

        lblJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Juego.jpg"))); // NOI18N
        getContentPane().add(lblJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void txtIngresarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngresarSaldoActionPerformed
        
    }//GEN-LAST:event_txtIngresarSaldoActionPerformed

    private void btnIngresarDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarDineroActionPerformed
        int saldoAIngresar = Integer.parseInt( txtIngresarSaldo.getText() );
        if( saldoAIngresar>0 ){
            this.saldoActual += saldoAIngresar;
            txtSaldo.setText(Integer.toString(this.saldoActual));
            txtIngresarSaldo.setText("");
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Ingrese un Saldo Valido");
    }//GEN-LAST:event_btnIngresarDineroActionPerformed

    private void btnCienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCienActionPerformed
        if(this.saldoActual >= 100){
            this.saldoActual -= 100;
            this.apuesta += 100;          
            txtApuesta.setText( Integer.toString(this.apuesta));
            txtSaldo.setText( Integer.toString(this.saldoActual));
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Su Saldo Actual es Insuficiente :(");
        
    }//GEN-LAST:event_btnCienActionPerformed

    private void btnMilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMilActionPerformed
        if(this.saldoActual >= 1000){
            this.saldoActual -= 1000;
            this.apuesta += 1000;          
            txtApuesta.setText( Integer.toString(this.apuesta));
            txtSaldo.setText( Integer.toString(this.saldoActual));
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Su Saldo Actual es Insuficiente :(");
    }//GEN-LAST:event_btnMilActionPerformed

    private void btnCincomilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincomilActionPerformed
        if(this.saldoActual >= 5000){
            this.saldoActual -= 5000;
            this.apuesta += 5000;          
            txtApuesta.setText( Integer.toString(this.apuesta));
            txtSaldo.setText( Integer.toString(this.saldoActual));
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Su Saldo Actual es Insuficiente :(");
    }//GEN-LAST:event_btnCincomilActionPerformed

    private void btnQuinientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuinientosActionPerformed
        if(this.saldoActual >= 500){
            this.saldoActual -= 500;
            this.apuesta += 500;          
            txtApuesta.setText( Integer.toString(this.apuesta));
            txtSaldo.setText( Integer.toString(this.saldoActual));
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Su Saldo Actual es Insuficiente :(");
    }//GEN-LAST:event_btnQuinientosActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        Random aleatorio = new Random(System.currentTimeMillis()); 
        timer = new Timer(); 
        
        cambiarIconos = new TimerTask() {
            @Override
            public void run() {                
                for (int i = 0; i < 3; i++) { // 3 NUMEROS ALEATORIOS
                    aleatorio.setSeed(aleatorio.nextLong());
                    int numImagen = aleatorio.nextInt(7);
                    switch (i) {
                        case 0:
                            lblImagen1.setIcon(selecImagen(numImagen, i));
                            break;
                        case 1:
                            lblImagen2.setIcon(selecImagen(numImagen, i));
                            break;
                        case 2:
                            lblImagen3.setIcon(selecImagen(numImagen, i));
                            break;
                    }
                }
                terminarJugada();
            }
        };            
        timer.scheduleAtFixedRate(cambiarIconos,0, 150);
        btnJugar.setEnabled(false);        
    }//GEN-LAST:event_btnJugarActionPerformed

    private void terminarJugada(){
        contador ++;
        if(contador>25){
            timer.cancel();
            contador=0;
            btnJugar.setEnabled(true); 
            //GANA
            if(numsImagenes[0] == numsImagenes[1] && numsImagenes[0] == numsImagenes[2]){
                JOptionPane.showMessageDialog(rootPane, "Felicitaciones, ¡Gano!");
                int ganado;
                switch(numsImagenes[0]){
                    case 0:                         
                        ganado= apuesta*3;                        
                        break;
                    case 1:
                        ganado= apuesta*3;
                        break;
                    case 2:
                        ganado= apuesta*4;
                        break;
                    case 3: 
                        ganado= apuesta*5;
                        break;
                    case 4:
                        ganado= apuesta*6;
                        break;
                    default:
                        ganado= apuesta*3;
                }
                saldoActual += ganado;
                txtSaldo.setText(Integer.toString(saldoActual) );                               
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Perdiste!");
            }
            apuesta = 0;
            txtApuesta.setText("0");                        
        }
    }    
       
    private Icon selecImagen(int numImagen, int i) {
        
        Icon imagen;
        if(numImagen>4)
            numImagen -= 5;
        this.numsImagenes[i]=numImagen;
        switch(numImagen){
            case 0: 
                imagen = new ImageIcon( getClass().getResource("/Imagenes/Campana.jpg"));
                break;
            case 1:
                imagen = new ImageIcon( getClass().getResource("/Imagenes/Cerezas.jpg"));
                break;
            case 2:
                imagen = new ImageIcon( getClass().getResource("/Imagenes/Sandia.jpg")); //Campana
                break;
            case 3:
                imagen = new ImageIcon( getClass().getResource("/Imagenes/Siete.jpg")); //Cerezas
                break;
            case 4:
                imagen = new ImageIcon( getClass().getResource("/Imagenes/Bar.jpg")); //Sandia
                break;  
            default:
                imagen = new ImageIcon( getClass().getResource("/Imagenes/Campana.jpg"));
        }
        
        return imagen;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCien;
    private javax.swing.JButton btnCincomil;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnIngresarDinero;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnMil;
    private javax.swing.JButton btnQuinientos;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblImagen2;
    private javax.swing.JLabel lblImagen3;
    private javax.swing.JLabel lblJuego;
    private javax.swing.JTextField txtApuesta;
    private javax.swing.JTextField txtIngresarSaldo;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
