/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogicaPresentacion;

import LogicaNegocios.Casino;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author dcast
 */
public class pnlAgregarMaquina extends javax.swing.JPanel {

    /**
     * Creates new form pnlAgregarMaquina
     */
    private Casino miCasino;
    private Component rootPane;
    public pnlAgregarMaquina() {
        miCasino = new Casino("BlackJack");
        initComponents();   
        listarJuegos();
    }
    
    private void listarJuegos(){
        ArrayList <Object[]> juegos;
        Object[] columnas ; 
        
        juegos = miCasino.listarJuegos();        
        for(int i=1; i<juegos.size(); i++){
            columnas = juegos.get(i);
            cmbNombreJuego.addItem(columnas[0].toString());        
        }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardarMaquina = new javax.swing.JButton();
        txtSerial = new javax.swing.JTextField();
        cmbNombreJuego = new javax.swing.JComboBox<>();
        cmbTipoDinero = new javax.swing.JComboBox<>();
        lblAgregarMaq = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarMaquina.setBackground(new java.awt.Color(51, 51, 51));
        btnGuardarMaquina.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnGuardarMaquina.setForeground(new java.awt.Color(255, 255, 51));
        btnGuardarMaquina.setText("Guardar");
        btnGuardarMaquina.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardarMaquina.setContentAreaFilled(false);
        btnGuardarMaquina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMaquinaActionPerformed(evt);
            }
        });
        add(btnGuardarMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 80, -1));

        txtSerial.setBackground(new java.awt.Color(51, 51, 51));
        txtSerial.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        txtSerial.setForeground(new java.awt.Color(255, 255, 255));
        txtSerial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(txtSerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 150, 20));

        cmbNombreJuego.setBackground(new java.awt.Color(51, 51, 51));
        add(cmbNombreJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 150, -1));

        cmbTipoDinero.setBackground(new java.awt.Color(51, 51, 51));
        cmbTipoDinero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monedas", "Billetes", "Monedas y Billetes" }));
        cmbTipoDinero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbTipoDinero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbTipoDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoDineroActionPerformed(evt);
            }
        });
        add(cmbTipoDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 150, -1));

        lblAgregarMaq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar Maquina.jpg"))); // NOI18N
        add(lblAgregarMaq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMaquinaActionPerformed
         String serial = txtSerial.getText();
         String juegoInstalado = cmbNombreJuego.getSelectedItem().toString();
         String tipoDinero = cmbTipoDinero.getSelectedItem().toString();
         int res = miCasino.registrarMaquina(serial, juegoInstalado, tipoDinero);
         if(res == 1){
            JOptionPane.showMessageDialog(rootPane, "Maquina Registrada Correctamente");
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Maquina No Registrada");
        txtSerial.setText("");
         
    }//GEN-LAST:event_btnGuardarMaquinaActionPerformed

    private void cmbTipoDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoDineroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoDineroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarMaquina;
    private javax.swing.JComboBox<String> cmbNombreJuego;
    private javax.swing.JComboBox<String> cmbTipoDinero;
    private javax.swing.JLabel lblAgregarMaq;
    private javax.swing.JTextField txtSerial;
    // End of variables declaration//GEN-END:variables
}
