/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogicaPresentacion;

/**
 *
 * @author dcast
 */
import LogicaNegocios.Casino;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
public class pnlBuscarMaquina extends javax.swing.JPanel {

    /**
     * Creates new form pnlBuscarMaquina
     */
    private Casino miCasino;
    public pnlBuscarMaquina() {
        miCasino= new Casino("BlackJack");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarMaquina = new javax.swing.JButton();
        txtSerial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusqueda = new javax.swing.JTable();
        lblBuscarMaquina = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarMaquina.setBackground(new java.awt.Color(51, 51, 51));
        btnBuscarMaquina.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnBuscarMaquina.setForeground(new java.awt.Color(255, 255, 51));
        btnBuscarMaquina.setText("Buscar");
        btnBuscarMaquina.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarMaquina.setContentAreaFilled(false);
        btnBuscarMaquina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMaquinaActionPerformed(evt);
            }
        });
        add(btnBuscarMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 80, -1));

        txtSerial.setBackground(new java.awt.Color(51, 51, 51));
        txtSerial.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        txtSerial.setForeground(new java.awt.Color(255, 255, 255));
        txtSerial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(txtSerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 170, -1));

        tblBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Serial", "Juego Instalado", "Tipo de Dinero", "Recaudado ($)", "Entregado ($)", "Utilidad ($)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBusqueda);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 610, 60));

        lblBuscarMaquina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EliminarMaquina.jpg"))); // NOI18N
        add(lblBuscarMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMaquinaActionPerformed
        String serial = txtSerial.getText();
        ArrayList <Object[]> maquinas;
        Object[] columnas;
        DefaultTableModel datos = new DefaultTableModel();
        this.tblBusqueda.setModel(datos);
        
        maquinas = miCasino.buscarMaquina(serial);
        columnas = maquinas.get(0);
        for(int i=0; i<columnas.length; i++)
            datos.addColumn(columnas[i]);
        
        for(int i=1; i<maquinas.size(); i++)
               datos.addRow(maquinas.get(i));
    }//GEN-LAST:event_btnBuscarMaquinaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarMaquina;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarMaquina;
    private javax.swing.JTable tblBusqueda;
    private javax.swing.JTextField txtSerial;
    // End of variables declaration//GEN-END:variables
}
