/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogicaPresentacion;

/**
 *
 * @author dcast
 */
public class pnlEliminarMaquina extends javax.swing.JPanel {

    /**
     * Creates new form pnlBuscarMaquina
     */
    public pnlEliminarMaquina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminarMaquina = new javax.swing.JButton();
        txtSerial = new javax.swing.JTextField();
        lblBuscarMaquina = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarMaquina.setBackground(new java.awt.Color(51, 51, 51));
        btnEliminarMaquina.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnEliminarMaquina.setForeground(new java.awt.Color(255, 255, 51));
        btnEliminarMaquina.setText("Eliminar");
        btnEliminarMaquina.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarMaquina.setContentAreaFilled(false);
        btnEliminarMaquina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnEliminarMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 80, -1));

        txtSerial.setBackground(new java.awt.Color(51, 51, 51));
        txtSerial.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        txtSerial.setForeground(new java.awt.Color(255, 255, 255));
        txtSerial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(txtSerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 170, -1));

        lblBuscarMaquina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EliminarMaquina.jpg"))); // NOI18N
        add(lblBuscarMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 330));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarMaquina;
    private javax.swing.JLabel lblBuscarMaquina;
    private javax.swing.JTextField txtSerial;
    // End of variables declaration//GEN-END:variables
}
