/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogicaPresentacion;

import java.awt.BorderLayout;

/**
 *
 * @author dcast
 */
public class pnlGJuegos extends javax.swing.JPanel {

    /**
     * Creates new form PanelOne
     */
    public pnlGJuegos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListarJuego = new javax.swing.JButton();
        btnEliminarJuego = new javax.swing.JButton();
        btnBuscarJuego = new javax.swing.JButton();
        btnAgregarJuego = new javax.swing.JButton();
        lblHome = new javax.swing.JLabel();
        lblJuegos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnListarJuego.setBorder(null);
        btnListarJuego.setBorderPainted(false);
        btnListarJuego.setContentAreaFilled(false);
        btnListarJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarJuegoActionPerformed(evt);
            }
        });
        add(btnListarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 40, 40));

        btnEliminarJuego.setBorder(null);
        btnEliminarJuego.setBorderPainted(false);
        btnEliminarJuego.setContentAreaFilled(false);
        btnEliminarJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarJuegoActionPerformed(evt);
            }
        });
        add(btnEliminarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 40, 40));

        btnBuscarJuego.setBorder(null);
        btnBuscarJuego.setBorderPainted(false);
        btnBuscarJuego.setContentAreaFilled(false);
        btnBuscarJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarJuegoActionPerformed(evt);
            }
        });
        add(btnBuscarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 40, 40));

        btnAgregarJuego.setBorder(null);
        btnAgregarJuego.setBorderPainted(false);
        btnAgregarJuego.setContentAreaFilled(false);
        btnAgregarJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarJuegoActionPerformed(evt);
            }
        });
        add(btnAgregarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, 40));
        add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 124, 720, 330));

        lblJuegos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GestionarJuegos.jpg"))); // NOI18N
        add(lblJuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarJuegoActionPerformed
        pnlAgregarJuego p1 = new pnlAgregarJuego();
        p1.setSize(720,330);
        p1.setLocation(-1,2);
        
        lblHome.removeAll();
        lblHome.add(p1,BorderLayout.CENTER);
        lblHome.revalidate();
        lblHome.repaint();
    }//GEN-LAST:event_btnAgregarJuegoActionPerformed

    private void btnBuscarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarJuegoActionPerformed
        pnlBuscarJuego p1 = new pnlBuscarJuego();
        p1.setSize(720,330);
        p1.setLocation(-1,2);
        
        lblHome.removeAll();
        lblHome.add(p1,BorderLayout.CENTER);
        lblHome.revalidate();
        lblHome.repaint();
    }//GEN-LAST:event_btnBuscarJuegoActionPerformed

    private void btnEliminarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarJuegoActionPerformed
        pnlEliminarJuego p1 = new pnlEliminarJuego();
        p1.setSize(720,330);
        p1.setLocation(-1,2);
        
        lblHome.removeAll();
        lblHome.add(p1,BorderLayout.CENTER);
        lblHome.revalidate();
        lblHome.repaint();
    }//GEN-LAST:event_btnEliminarJuegoActionPerformed

    private void btnListarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarJuegoActionPerformed
        pnlListarJuego p1 = new pnlListarJuego();
        p1.setSize(720,330);
        p1.setLocation(-1,2);
        
        lblHome.removeAll();
        lblHome.add(p1,BorderLayout.CENTER);
        lblHome.revalidate();
        lblHome.repaint();
    }//GEN-LAST:event_btnListarJuegoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarJuego;
    private javax.swing.JButton btnBuscarJuego;
    private javax.swing.JButton btnEliminarJuego;
    private javax.swing.JButton btnListarJuego;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblJuegos;
    // End of variables declaration//GEN-END:variables
}
