/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogicaPresentacion;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import LogicaAccesoDatos.GestorBD;
import LogicaNegocios.Casino;

/**
 *
 * @author dcast
 */
public class pnlListarMaquina extends javax.swing.JPanel {

    /**
     * Creates new form pnlListarJuego
     */
    private Casino miCasino;
    public pnlListarMaquina() {
        initComponents();
        miCasino = new Casino();
        listar();
    }
    
    public void listar(){
        ArrayList <Object[]> maquinas;
        Object[] columnas;
        DefaultTableModel datos = new DefaultTableModel();
        tblListaMaquinas.setModel(datos);
        
        maquinas = miCasino.listarMaquinasAll();
        columnas = maquinas.get(0);
        for(int i=0; i<columnas.length; i++)
            datos.addColumn(columnas[i]);
        
        for(int i=1; i<maquinas.size(); i++)
            datos.addRow(maquinas.get(i));
        
        tblListaMaquinas.setSelectionMode(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaMaquinas = new javax.swing.JTable();
        lblListarJuego = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblListaMaquinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Serial", "Juego Instalado", "Tipo de Dinero", "Recaudado ($)", "Entregado ($)", "Utilidad ($)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListaMaquinas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 650, 190));

        lblListarJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ListarJuego.jpg"))); // NOI18N
        add(lblListarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 330));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListarJuego;
    private javax.swing.JTable tblListaMaquinas;
    // End of variables declaration//GEN-END:variables
}
