/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogicaPresentacion;

/**
 *
 * @author dcast
 */
public class pnlListarJuego extends javax.swing.JPanel {

    /**
     * Creates new form pnlListarJuego
     */
    public pnlListarJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblListarJuego = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblListarJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ListarJuego.jpg"))); // NOI18N
        add(lblListarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 330));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblListarJuego;
    // End of variables declaration//GEN-END:variables
}
